export { default as Home } from "./Home"
export { default as Discover } from "./Discover"
export { default as Profile } from "./Profile"
export { default as ProjectDetails } from "./ProjectDetails"
export { default as CreateProject } from "./CreateProject"
export { default as AboutUs } from "./AboutUs"
export { default as Login } from "./Login"
export { default as Signup } from "./Signup"